### ISSUE TITLE
Create tasks

### ISSUE THREAD

**Issue by SenhorBardell** [SenhorBardell/rails-administrator#1]
# Task list

- [x] Create initial tasks
- [x] Create wiki pages
- [x] Set up initial repository
- [x] Set up integration with circle ci
- [x] Set up deploy to heroku

# Deliverables

- [x] Github repository
- [x] Heroku project
- [x] Wiki
- [x] Issues
- [x] Projects
