### ISSUE TITLE
User page

### ISSUE THREAD

**Issue by SenhorBardell** [SenhorBardell/rails-administrator#10]
# Description 

A user page that will show a user's fields with the ability to update them.

# Task list

- [ ] create user details page component
- [ ] display user fields from api
- [ ] update user action
- [ ] send pdf action

# Deliverables

- [ ] user details page component
- [ ] user details unit test
- [ ] user details ui test
