### ISSUE TITLE
Use paperclip for storing user images

### ISSUE THREAD

**Issue by SenhorBardell** [SenhorBardell/rails-administrator#11]
# Task list

- [ ] add paperclip to back end
- [ ] add migration
- [ ] update user model

# Deliverables

- [ ] updated rails configuration
- [ ] updated user model
- [ ] updated unit tests
