### ISSUE TITLE
Research role based solution for back-end

### ISSUE THREAD

**Issue by SenhorBardell** [SenhorBardell/rails-administrator#13]
# Description

Decide what approach should be takes for using role base authorization. Double check the preferred rails conventions, use standart functionality if applicable. Otherwise use [acl9](https://github.com/be9/acl9)

# Task list

- [x] research available options
- [x] decide on one

# Deliverables

- [x] role based authorization solution and wiki page 
- [x] task describing what and how do role based auth
