### ISSUE TITLE
Integrate Capibara

### ISSUE THREAD

**Issue by SenhorBardell** [SenhorBardell/rails-administrator#14]
# Description

Start by integration [capybara](https://github.com/teamcapybara/capybara) into rails backend. Use shiny new chrome driver if possible.

# Task list

- [ ] integrate capybara with rspec or make separate rake task if ci integration is not possible (or expensive)
- [ ] make sure tests are green

# Deliverables

- [ ] rspec capybara integration
