### ISSUE TITLE
Create initial React frontend

### ISSUE THREAD

**Issue by SenhorBardell** [SenhorBardell/rails-administrator#15]
# Task list

- [x] research rails react integration
- [x] create sample welcome page
- [x] create sample jester unit test

# Deliverables

- [x] the app has a face
