### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by SenhorBardell** [SenhorBardell/rails-administrator#2]
# Task list

- [ ] Write database schema page
- [ ] Generate initial database schema
- [ ] Apply migration

# Expected deliverables:
- [ ] user model file
- [ ] user migration file
- [ ] role model file
- [ ] role migration file

**Comment by SenhorBardell** [comment]
#16
