### ISSUE TITLE
Create controllers

### ISSUE THREAD

**Issue by SenhorBardell** [SenhorBardell/rails-administrator#3]
# Task list

- [x] Generate simple crud controller for user
- [x] Generate/verify initial tests and make sure they are passing

# Expected deliverables

- [x] user controller with create, read, update, delete rest endpoints
- [x] rspec initial tests for user controller
