### ISSUE TITLE
Create project specification

### ISSUE THREAD

**Issue by SenhorBardell** [SenhorBardell/rails-administrator#4]
# Task list

- [x] write project description
- [x] outline required project specifications based on description
- [x] describe technologies that will be used in project

# Expected deliverables

- [x] new wiki page – `Project specification`
