### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by SenhorBardell** [SenhorBardell/rails-administrator#5]
# Task list

- [ ] on user creation generate token
- [ ] basic user authentication

# Deliverables

- [ ] new/updated test cases
