### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by SenhorBardell** [SenhorBardell/rails-administrator#6]
# Task list

- [ ] create welcome page component

# Expected deliverables

- [ ] welcome page component
- [ ] welcome page test
