### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by SenhorBardell** [SenhorBardell/rails-administrator#7]
# Description

Basic user login form. User should be able to input his email and password. Upon triggering log in button, should receive authorization token, save it to localStorage, redirect to welcome page.

# Task list

- [ ] create login page component
- [ ] create login action
- [ ] create unit tests
- [ ] create ui tests

# Deliverables

- [ ] login page component
- [ ] page component unit test
- [ ] page ui test

Depends on #5, #6
