### ISSUE TITLE
Registration page

### ISSUE THREAD

**Issue by vladchatware** [SenhorBardell/rails-administrator#8]
# Description

User should able to update its properties. (email, first name, last name, birthdate, bio)

# Task list

- [x] create registration page component
- [x] create validation cases

# Deliverables

- [x] registration page component
- [ ] page unit test
- [ ] page ui test
