### ISSUE TITLE
Dashboard page

### ISSUE THREAD

**Issue by SenhorBardell** [SenhorBardell/rails-administrator#9]
# Description

Dashboard page should display a list of users. Should only be accessible to admin users. Admin user can click on user in list and should be directed to edit user page.

# Task list

- [ ] create dashboard page component
- [ ] display a list of users from api

# Deliverables

- [ ] dashboard page component
- [ ] unit test for dashboard component
- [ ] ui test for page
